<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>0.0.0.39</Version>
    <PackageProjectUrl>https://aethertek.io/</PackageProjectUrl>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
    <XAExtraDefineConstants></XAExtraDefineConstants>
    <DefineConstants Condition="'$(XAExtraDefineConstants)' != ''">$(DefineConstants);$(XAExtraDefineConstants)</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <PathMap>$(MSBuildProjectDirectory)=/_/XASlave</PathMap>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="backups\**" />
    <Compile Remove="**\backups\**" />
    <None Remove="backups\**" />
    <None Remove="**\backups\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.3" />
    <PackageReference Include="NAudio.Core" Version="2.2.1" />
    <PackageReference Include="NAudio.Wasapi" Version="2.2.1" />
  </ItemGroup>
  <ItemGroup>
    <None Include="images\**" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Data\EurekaLogogramCreator\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
